import {build} from 'esbuild';
import {readFile,writeFile,stat} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
import {gzipSync,gunzipSync} from 'node:zlib';
const here=fileURLToPath(new URL('.',import.meta.url));
const root=path.resolve(here,'..');
const readJSON=async file=>JSON.parse(await readFile(path.join(root,file),'utf8'));
const model=await readJSON('assets/model/iphone-duo.gltf');
const lighting=await readJSON('assets/lighting/lighting-config.json');
const packed=await readJSON('assets/lighting/linear-exr-manifest.json');
const files=new Map();
function add(url,variant,extra={}){files.set(url,{url:'./'+url,...(variant?{variant}:{}),...extra});}
add('assets/model/iphone-duo.gltf');
for(const value of model.buffers)if(value.uri&&!value.uri.startsWith('data:')){
  const original='assets/model/'+value.uri;
  const raw=await readFile(path.join(root,original));
  const compressed=gzipSync(raw,{level:9});
  if(!gunzipSync(compressed).equals(raw))throw new Error('Model compression changed the geometry.');
  await writeFile(path.join(root,original+'.gz'),compressed);
  add(original,'exr');
  add(original+'.gz','packed',{logicalUrl:'./'+original,decode:'gzip',decodedBytes:raw.length});
}
for(const value of model.images)if(value.uri&&!value.uri.startsWith('data:'))add('assets/model/'+value.uri);
add('assets/lighting/lighting-config.json');
for(const value of lighting.textures)add('assets/lighting/'+value.file);
for(const value of lighting.exrs)add('assets/lighting/'+value.file,'exr');
// The packed metadata format is generated by precompute-lighting.mjs.
for(const value of packed.files)add('assets/lighting/'+value.file,'packed',{decodedBytes:value.rawBytes});
for(const file of ['wallpaper-raccoon.webp','lockscreen-inner.avif','lockscreen-outer.avif'])add('assets/'+file);
for(const [file,entry] of files)entry.bytes=(await stat(path.join(root,file))).size;
await writeFile(path.join(root,'assets/load-manifest.json'),JSON.stringify({files:[...files.values()]})+'\n');
await build({entryPoints:[path.join(here,'main.js')],bundle:true,minify:true,format:'esm',target:'es2022',outfile:path.join(root,'app.js')});
await writeFile(path.join(root,'ar/app.js'),"// Compatibility for previously cached AR test pages.\nimport '../app.js?v=duo-2';\n");
