// Download progress uses a build-generated byte inventory, never a timer.
// The last 15% represents the preparation gates and first successful frame.
import {LoadingManager} from 'three';

// HTML and scripts can expire from browser caches at different times. Upgrade
// the previous /duo and /duo/ar markup before using the new loading controls.
export async function ensureLoadingMarkup() {
  const root=document.getElementById('loading');
  const missingProgress=!root.querySelector('[role="progressbar"]');
  const missingControls=!document.getElementById('loop-toggle');
  if(!missingProgress&&!missingControls)return;
  const stylesheet=document.createElement('link');
  stylesheet.rel='stylesheet';stylesheet.href=new URL('./style.css?v=4',document.baseURI).href;
  await new Promise(resolve=>{
    stylesheet.onload=stylesheet.onerror=resolve;
    document.head.appendChild(stylesheet);
  });
  if(missingProgress)root.innerHTML='<p class="loading-title">Loading 3D model…</p><div class="loading-meter" role="progressbar" aria-label="3D model loading progress" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><span id="loading-bar"></span></div><p class="loading-detail"><span id="loading-phase">Downloading model</span><span id="loading-percent" aria-hidden="true">0%</span></p>';
  if(missingControls){
    const actions=document.createElement('div');actions.className='ar-actions';
    actions.innerHTML='<button id="loop-toggle" disabled type="button" aria-label="Pause folding animation">Pause loop</button><a id="ar-link" hidden>Try it in Augmented Reality</a>';
    const status=document.createElement('p');status.id='ar-status';status.hidden=true;status.setAttribute('role','status');status.setAttribute('aria-live','polite');
    document.querySelector('.slider-dock').append(actions,status);
  }
  document.getElementById('stage').setAttribute('aria-busy','true');
  document.getElementById('fold').disabled=true;
  document.getElementById('loop-toggle').disabled=true;
}

export function createLoadingUI() {
  const root = document.getElementById('loading');
  const meter = root.querySelector('[role="progressbar"]');
  const percent = document.getElementById('loading-percent');
  const phase = document.getElementById('loading-phase');
  const bar = document.getElementById('loading-bar');
  let current = 0;
  function update(value, label) {
    current = Math.max(current, Math.min(100, Math.floor(value)));
    percent.textContent = `${current}%`;
    meter.setAttribute('aria-valuenow', String(current));
    bar.style.transform = `scaleX(${current / 100})`;
    if (label && phase.textContent !== label) phase.textContent = label;
  }
  return {update, complete() {
    update(100, 'Ready');
    document.getElementById('stage').setAttribute('aria-busy', 'false');
    document.body.classList.add('ready');
    root.setAttribute('aria-label', '3D phone ready');
  }};
}

// Let the loading UI paint before synchronous GPU/geometry preparation.
export function yieldToMain() {
  return new Promise(resolve => requestAnimationFrame(() => setTimeout(resolve, 0)));
}

export async function preloadAssets(update) {
  const response = await fetch('./assets/load-manifest.json');
  if (!response.ok) throw new Error(`Asset inventory: HTTP ${response.status}`);
  const manifest = await response.json();
  const usePackedAssets = typeof DecompressionStream === 'function';
  const files = manifest.files.filter(file => !file.variant || file.variant === (usePackedAssets ? 'packed' : 'exr'));
  const total = files.reduce((sum, file) => sum + file.bytes, 0);
  const objects = new Map();
  const controller = new AbortController();
  let downloaded = 0, cursor = 0;
  const absolute = path => new URL(path, document.baseURI).href;
  const dispose = () => {for (const url of objects.values()) URL.revokeObjectURL(url);objects.clear();};
  async function worker() {
    while (cursor < files.length) {
      const file = files[cursor++];
      const path = absolute(file.url);
      const response = await fetch(path, {signal: controller.signal});
      if (!response.ok) throw new Error(`3D asset: HTTP ${response.status}`);
      const chunks = [];
      // Some hosts decode .gz files through Content-Encoding before fetch
      // exposes the stream. Weight those decoded bytes by their packed size.
      const expectedBytes=file.decodedBytes&&response.headers.get('content-encoding')?.includes('gzip')?file.decodedBytes:file.bytes;
      let received = 0, credited = 0;
      const credit = length => {
        received += length;
        const loaded = Math.min(file.bytes,received / expectedBytes * file.bytes);
        downloaded += loaded - credited;credited = loaded;
        update(Math.min(85, downloaded / total * 85), 'Downloading model');
      };
      if (response.body) {
        const reader = response.body.getReader();
        while (true) {
          const {done, value} = await reader.read();
          if (done) break;
          chunks.push(value);credit(value.byteLength);
        }
      } else {
        const value = await response.arrayBuffer();
        chunks.push(value);credit(value.byteLength);
      }
      if (received !== expectedBytes) throw new Error('A 3D asset was incomplete. Reload to try again.');
      let blob = new Blob(chunks, {type: response.headers.get('content-type') || 'application/octet-stream'});
      if(file.decode==='gzip'){
        const signature=new Uint8Array(await blob.slice(0,2).arrayBuffer());
        if(signature[0]===0x1f&&signature[1]===0x8b)blob=await new Response(blob.stream().pipeThrough(new DecompressionStream('gzip'))).blob();
        if(blob.size!==file.decodedBytes)throw new Error('The 3D geometry was incomplete. Reload to try again.');
      }
      if(controller.signal.aborted)throw new DOMException('Loading cancelled','AbortError');
      objects.set(absolute(file.logicalUrl||file.url), URL.createObjectURL(blob));
    }
  }
  try {await Promise.all(Array.from({length: 6}, worker));}
  catch (error) {controller.abort();dispose();throw error;}
  update(85, 'Preparing 3D view');
  const url = path => objects.get(absolute(path)) || path;
  const manager = new LoadingManager();
  manager.setURLModifier(url);
  return {manager, url, dispose, downloaded, total};
}
