const escapeHTML = value => String(value).replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const link = (url, text) => `<a href="${escapeHTML(url)}" target="_blank" rel="noopener noreferrer">${escapeHTML(text)} ↗</a>`;
const source = {
  water:'https://www.observatoire-eau-guadeloupe.fr/content/uploads/2026/01/Chiffres_Cles_AEP-EU_2025_Rapport.pdf',
  balance:'https://www.observatoire-eau-guadeloupe.fr/services-publics-eau-assainissement/eau-potable/',
  audit:'https://www.ccomptes.fr/sites/default/files/2025-07/RAN2025-0280.pdf',
  roadBackup:'https://www.guadeloupe.developpement-durable.gouv.fr/accidentalite-remontees-rapides-a305.html',
  roadDefinition:'https://www.onisr.securite-routiere.gouv.fr/glossaire',
  roadMethod:'https://www.onisr.securite-routiere.gouv.fr/sites/default/files/2022-08/Barometre_juillet_2022_ONISR.pdf',
  chlordecone:'https://www.ameli.fr/assure/sante/themes/chlordecone/chlordecone-sante',
  sargassum:'https://www.brgm.fr/fr/reference-projet-acheve/epandage-sargasses-guadeloupe-impact-environnemental-sites',
};
const date = (value, lang) => new Intl.DateTimeFormat(lang === 'fr' ? 'fr-FR' : 'en-GB', {day:'numeric',month:'long',year:'numeric',timeZone:'America/Guadeloupe'}).format(new Date(value+'T12:00:00Z'));
export const COPY = {
 fr: {
  headline:'Guadeloupe — Eau et vies perdues.',waterUnits:'litres perdus aujourd’hui',flow:'L/sec (Est. 2023)',
  homicides:'Homicides',roads:'Sur les routes',reported:'bilans rapportés',deaths:year=>`Décès en ${year}`,
  cta:'Comprendre ces chiffres',details:'Derrière les chiffres',close:'Fermer',language:'Langue',dayShare:'de la journée',fullBottle:'Bouteille pleine',
  footer:'L’eau est estimée. Les décès sont des bilans datés.',archive:year=>`Eau : estimation quotidienne · Décès : archive ${year}`,
  figure:'Une bouteille, un pistolet et une roue sur la carte de la Guadeloupe',sceneRole:'objets 3D interactifs',
  scene:'Faites glisser horizontalement sur un objet pour le tourner. Les flèches inclinent la bouteille. R recentre les trois objets.',
  waterAria:'Estimation des litres perdus ou non comptabilisés aujourd’hui en Guadeloupe',deathAria:year=>`Somme des deux bilans de décès rapportés en ${year}`,
  graphicsError:'La vue 3D est indisponible. Les chiffres restent accessibles.',dataLoading:'Chargement des bilans de décès…',dataError:'Le bilan de décès est momentanément indisponible. L’estimation d’eau reste active.',
  title:'Gwada Stats — L’eau et les vies perdues | Manu.Vision',description:'L’eau perdue, les homicides et les décès routiers en Guadeloupe. Une expérience 3D fondée sur des sources publiques et des bilans datés.',
  modal:(s,SNAPSHOT)=>`<p class="intro">Je suis originaire de la Caraïbe. J’ai voulu réunir ici l’eau qui se perd dans les réseaux, et les vies perdues dans les violences et sur les routes. Trois chiffres pour regarder ce qui se passe chez nous.</p>
<section><h3>L’eau perdue aujourd’hui</h3><p>Le bilan 2023 compte <strong>76,9 millions de m³ distribués</strong> et <strong>32,3 millions comptabilisés comme consommés</strong>. La différence représente <strong>44,6 milliards de litres sur l’année</strong>, soit environ <strong>122,2 millions par jour</strong> et 58 % du volume distribué.</p><p>Ce sont des fuites, mais aussi de l’eau consommée et mal comptée : compteurs défectueux, fichiers incomplets ou branchements non autorisés. Les fuites après le compteur des usagers sont exclues.</p>${link(source.water,'Observatoire de l’eau · bilan 2023, publication 2025')}${link(source.balance,'Distribution, pertes et eau non comptabilisée')}</section>
<section><h3>La bouteille suit la journée</h3><p>Une bouteille pleine représente cette journée moyenne. À midi en Guadeloupe, elle est à moitié pleine. Son pourcentage est celui de la journée écoulée, <strong>pas le taux de perte du réseau</strong>. Elle repart à zéro à minuit, heure de Guadeloupe (UTC−4).</p><p>Le compteur applique la moyenne de 2023 aux secondes écoulées. <strong>Il ne mesure pas les pertes réelles d’aujourd’hui.</strong> Les réparations, coupures et variations de pression du jour ne sont pas prises en compte.</p></section>
<section><h3>${s.total} décès rapportés en ${s.year}</h3><div class="formula">${s.homicides} homicides + ${s.roads} décès routiers = ${s.total}</div><p>Les deux bilans commencent au 1er janvier, mais s’arrêtent à des dates différentes. Leur somme <strong>n’est pas un décompte exact à aujourd’hui, ni le total de tous les décès</strong>. Aucun décès n’est extrapolé avec l’horloge.</p></section>
<section><h3>${s.homicides} homicides · ${date(SNAPSHOT.homicides.asOf,'fr')}</h3><p>${escapeHTML(SNAPSHOT.homicides.publisher)} rapporte ce bilan en Guadeloupe, hors Saint-Martin. Il ne s’agit ni de tentatives ni d’un bilan judiciaire définitif. L’article ne fournit pas de registre individuel. Le pistolet est un symbole : <strong>tous ces homicides ne sont pas des morts par balle</strong>.</p>${link(SNAPSHOT.homicides.source,`${SNAPSHOT.homicides.publisher} · publication du ${date(SNAPSHOT.homicides.publishedAt,'fr')}`)}</section>
<section><h3>${s.roads} décès routiers · ${date(SNAPSHOT.roads.asOf,'fr')}</h3><p>${escapeHTML(SNAPSHOT.roads.publisher)} rapporte ce bilan provisoire pour la Guadeloupe, hors Saint-Martin et Saint-Barthélemy. Il inclut les automobilistes, passagers, deux-roues, cyclistes et piétons décédés dans les 30 jours après un accident.</p>${link(SNAPSHOT.roads.source,`${SNAPSHOT.roads.publisher} · bilan au ${date(SNAPSHOT.roads.asOf,'fr')}`)}${link(source.roadBackup,'DEAL · suivi routier')}${link(source.roadDefinition,'ONISR · définitions')}<p>Les statistiques routières excluent les actes intentionnels, dont les homicides et suicides. Le bilan « Homicides » reprend les violences mortelles rapportées par la source citée. Les décès accidentels sur la route apparaissent séparément, dans « Sur les routes ».</p>${link(source.roadMethod,'ONISR · périmètre, p. 6')}</section>
<section><h3>Ce que ces chiffres laissent de côté</h3><p>Les bilans de décès peuvent évoluer ou être corrigés. Une vérification quotidienne est programmée. Les chiffres changent lorsqu’un nouveau bilan fiable est vérifié ; aucun décès n’est inventé entre deux publications. La carte situe l’archipel ; elle ne localise ni les victimes ni les fuites.</p><p>Pour l’eau, la chambre régionale des comptes décrit un réseau trop peu renouvelé, des variations de pression et des défaillances de gestion. Le bilan ne permet pas d’attribuer une quantité précise à la corrosion des tuyaux.</p>${link(source.audit,'Chambre régionale des comptes · rapport 2025, p. 39 et 117')}</section>
<section><h3>La qualité de l’eau, les sols et le littoral</h3><p>La chlordécone, utilisée dans les bananeraies de Guadeloupe et de Martinique jusqu’en 1993, contamine encore des sols et des milieux aquatiques. Sur le littoral, la décomposition des sargasses libère des gaz nocifs.</p><p>Ces sujets font partie de l’histoire de l’eau en Guadeloupe. Ils ne sont pas inclus dans le compteur, qui porte sur le bilan du réseau d’eau potable.</p>${link(source.chlordecone,'Assurance Maladie · chlordécone')}${link(source.sargassum,'BRGM · sargasses')}</section>
<p class="credit">Vérifications : homicides le ${date(SNAPSHOT.homicides.checkedAt ?? SNAPSHOT.reviewedAt,'fr')}, routes le ${date(SNAPSHOT.roads.checkedAt ?? SNAPSHOT.reviewedAt,'fr')}. Sources sur l’eau consultées le 9 septembre 2026. Carte Etalab / IGN, extrusion illustrative. ${link('../dlo/map-attribution.txt','Source et licence de la carte')}</p>`,
 },
 en: {
  headline:'Guadeloupe — Water and lives lost.',waterUnits:'litres lost today',flow:'L/sec (Est. 2023)',
  homicides:'Homicides',roads:'Road deaths',reported:'reported tallies',deaths:year=>`Deaths in ${year}`,
  cta:'Understand the numbers',details:'Behind the numbers',close:'Close',language:'Language',dayShare:'of the day',fullBottle:'Full bottle',
  footer:'Water is estimated. Deaths come from dated reports.',archive:year=>`Water: daily estimate · Deaths: ${year} archive`,
  figure:'A bottle, a handgun and a wheel over the map of Guadeloupe',sceneRole:'interactive 3D objects',
  scene:'Drag horizontally on an object to rotate it. Arrow keys tilt the bottle. R resets all three objects.',
  waterAria:'Estimated litres lost or unaccounted for today in Guadeloupe',deathAria:year=>`Sum of the two reported death tallies in ${year}`,
  graphicsError:'The 3D view is unavailable. The figures remain accessible.',dataLoading:'Loading death reports…',dataError:'The death tally is temporarily unavailable. The water estimate remains active.',
  title:'Gwada Stats — Water and lives lost | Manu.Vision',description:'Water losses, homicides and road deaths in Guadeloupe. A 3D experience based on public sources and dated reports.',
  modal:(s,SNAPSHOT)=>`<p class="intro">I’m from the Caribbean. I wanted to bring together the water lost in our networks, and the lives lost to violence and on our roads. Three figures to look at what is happening at home.</p>
<section><h3>Water lost today</h3><p>The 2023 balance reports <strong>76.9 million m³ distributed</strong> and <strong>32.3 million accounted as consumed</strong>. The difference is <strong>44.6 billion litres that year</strong>: about <strong>122.2 million a day</strong>, or 58% of the distributed volume.</p><p>This includes leaks and consumed water that is poorly accounted for: faulty meters, incomplete records and unauthorized connections. Leaks after customers’ meters are excluded.</p>${link(source.water,'Water Observatory · 2023 balance, 2025 publication')}${link(source.balance,'Distribution, losses and unaccounted-for water')}</section>
<section><h3>The bottle follows the day</h3><p>A full bottle represents this average day. At noon in Guadeloupe, it is half full. Its percentage shows how much of the day has passed, <strong>not the network’s loss rate</strong>. It starts again at midnight in Guadeloupe (UTC−4).</p><p>The counter applies the 2023 average to elapsed seconds. <strong>It does not measure today’s actual losses.</strong> Today’s repairs, cuts and pressure changes are not included.</p></section>
<section><h3>${s.total} reported deaths in ${s.year}</h3><div class="formula">${s.homicides} homicides + ${s.roads} road deaths = ${s.total}</div><p>Both tallies start on January 1 but have different cutoff dates. Their sum <strong>is not an exact count through today or a count of all deaths</strong>. No deaths are projected from the clock.</p></section>
<section><h3>${s.homicides} homicides · ${date(SNAPSHOT.homicides.asOf,'en')}</h3><p>${escapeHTML(SNAPSHOT.homicides.publisher)} reports this Guadeloupe tally, excluding Saint-Martin. It is neither a count of attempts nor a final judicial tally. The article has no individual register. The handgun is a symbol: <strong>these are not all firearm deaths</strong>.</p>${link(SNAPSHOT.homicides.source,`${SNAPSHOT.homicides.publisher} · published ${date(SNAPSHOT.homicides.publishedAt,'en')}`)}</section>
<section><h3>${s.roads} road deaths · ${date(SNAPSHOT.roads.asOf,'en')}</h3><p>${escapeHTML(SNAPSHOT.roads.publisher)} reports this provisional Guadeloupe tally, excluding Saint-Martin and Saint-Barthélemy. It includes drivers, passengers, motorcyclists, cyclists and pedestrians who died within 30 days of a crash.</p>${link(SNAPSHOT.roads.source,`${SNAPSHOT.roads.publisher} · tally through ${date(SNAPSHOT.roads.asOf,'en')}`)}${link(source.roadBackup,'DEAL · road monitoring')}${link(source.roadDefinition,'ONISR · definitions')}<p>Road statistics exclude intentional acts, including homicide and suicide. The “Homicides” figure reflects the cited source’s reported fatal-violence tally. Fatal road crashes appear separately under “Road deaths”.</p>${link(source.roadMethod,'ONISR · scope, p. 6')}</section>
<section><h3>What the figures leave out</h3><p>Death tallies can grow or be corrected. A daily source check is scheduled. Figures change when a reliable new tally is verified; no deaths are invented between publications. The map locates the archipelago, not victims or leaks.</p><p>For water, the regional audit office describes insufficient pipe replacement, pressure changes and management failures. The balance cannot assign a specific volume to pipe corrosion.</p>${link(source.audit,'Regional audit office · 2025 report, pp. 39 and 117')}</section>
<section><h3>Water quality, soils and the coast</h3><p>Chlordecone, used on banana plantations in Guadeloupe and Martinique until 1993, still contaminates soils and aquatic environments. On the coast, decomposing sargassum releases harmful gases.</p><p>These issues belong in Guadeloupe’s water story. They are not included in the counter, which covers the drinking-water network balance.</p>${link(source.chlordecone,'Assurance Maladie · chlordecone')}${link(source.sargassum,'BRGM · sargassum')}</section>
<p class="credit">Source checks: homicides on ${date(SNAPSHOT.homicides.checkedAt ?? SNAPSHOT.reviewedAt,'en')}, roads on ${date(SNAPSHOT.roads.checkedAt ?? SNAPSHOT.reviewedAt,'en')}. Water sources reviewed September 9, 2026. Etalab / IGN map, illustrative extrusion. ${link('../dlo/map-attribution.txt','Map source and licence')}</p>`,
 },
};
