import * as THREE from 'three';
import {createVillage} from './world.js';
import {anchors,setGroundPose,groundSprite} from './grounding.js';
const $=s=>document.querySelector(s),canvas=$('#world');
const renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(39,1,.1,100);camera.position.set(-2,9.2,14.15);let zoom=1;
const clock=new THREE.Clock(),village=createVillage(scene),interactables=village.interactables;function mesh(g,m,x=0,y=0,z=0){const o=new THREE.Mesh(g,m);o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;scene.add(o);return o;}
// One mesh per actor, with the approved image pixels and authored pivots preserved.
const loader=new THREE.TextureLoader();const names=['raccoon-master','raccoon-machete','raccoon-roll'];const sheets={};
try{await Promise.all(names.map(async n=>{const [texture,data]=await Promise.all([loader.loadAsync('../hd2d/assets/'+n+'.png'),fetch('../hd2d/assets/'+n+'.json').then(r=>{if(!r.ok)throw Error(n);return r.json()})]);texture.colorSpace=THREE.SRGBColorSpace;texture.magFilter=texture.minFilter=THREE.NearestFilter;texture.generateMipmaps=false;sheets[n]={texture,data};}));}catch(e){$('#loading').textContent='The sprites could not load. Please reload to try again.';throw e;}
const actorMat=new THREE.MeshStandardMaterial({map:sheets['raccoon-master'].texture,alphaTest:.5,roughness:1,side:THREE.DoubleSide});
const actor=mesh(new THREE.PlaneGeometry(1,1),actorMat,0,0,1.5);actor.castShadow=true;actor.receiveShadow=true;
actor.customDepthMaterial=new THREE.MeshDepthMaterial({depthPacking:THREE.RGBADepthPacking,map:actorMat.map,alphaTest:.5,side:THREE.DoubleSide});
const player={x:-2,z:.65,dir:'south',action:'idle',elapsed:0,walkTime:0};const pixel=.066,keys=new Set();let joystick={x:0,z:0},nearby=null,modal=false,collisions=0,rollVector={x:0,z:0},queuedRoll=false,rollStarts=0;
const movement={base:1.9,walkMultiplier:1.15,runMultiplier:1.30};
const shadowMat=new THREE.ShaderMaterial({transparent:true,depthWrite:false,uniforms:{},vertexShader:'varying vec2 vUv;void main(){vUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:'varying vec2 vUv;void main(){float a=(1.-smoothstep(.1,.5,length(vUv-.5)))*.38;gl_FragColor=vec4(.025,.018,.012,a);}'});
const shadow=mesh(new THREE.PlaneGeometry(1.02,.56),shadowMat);shadow.rotation.x=-Math.PI/2;shadow.castShadow=false;
const dirs={south:[0,1],east:[1,0],north:[0,-1],west:[-1,0]};
const durations={attack:[80,60,40,50,70,80,100],roll:[60,60,70,60,70,70,60,90]};
let lastPose='';function pose(){let n='raccoon-master',f,mirror=false,index=0;if(player.action==='attack'||player.action==='roll'){n=player.action==='roll'?'raccoon-roll':'raccoon-machete';const frames=sheets[n].data.frames.filter(f=>f.filename.startsWith(player.action+'_'+player.dir+'_'));let elapsed=player.elapsed*1000;index=0;while(index<frames.length-1&&elapsed>=durations[player.action][index]){elapsed-=durations[player.action][index++];}f=frames[index];}else{n='raccoon-machete';const clip=(player.action==='walk'?'walk':'idle')+'_'+player.dir+'_';const frames=sheets[n].data.frames.filter(f=>f.filename.startsWith(clip));index=player.action==='walk'?Math.floor(player.walkTime/.16)%4:0;f=frames[index];}const id=n+f.filename+player.dir;if(id===lastPose)return;lastPose=id;const r=f.frame,p=f.pivot||{x:8,y:32},t=sheets[n].texture,iw=t.image.width,ih=t.image.height;
t.repeat.set((mirror?-1:1)*r.w/iw,r.h/ih);t.offset.set((r.x+(mirror?r.w:0))/iw,1-(r.y+r.h)/ih);actorMat.map=t;actorMat.needsUpdate=true;actor.customDepthMaterial.map=t;actor.customDepthMaterial.needsUpdate=true;
setGroundPose(actor,f,anchors[n][f.filename],pixel);}
function blocked(x,z){return village.blocked(x,z);}
function move(dx,dz){if(!blocked(player.x+dx,player.z))player.x+=dx;else if(dx)collisions++;if(!blocked(player.x,player.z+dz))player.z+=dz;else if(dz)collisions++;}
function dismiss(){$('#dialog').hidden=true;modal=false;keys.clear();}
function startRoll(){const x=(keys.has('ArrowRight')||keys.has('KeyD')?1:0)-(keys.has('ArrowLeft')||keys.has('KeyA')?1:0)+joystick.x,z=(keys.has('ArrowDown')||keys.has('KeyS')?1:0)-(keys.has('ArrowUp')||keys.has('KeyW')?1:0)+joystick.z;if(Math.hypot(x,z)>.15)player.dir=Math.abs(x)>Math.abs(z)?x>0?'east':'west':z>0?'south':'north';const [dx,dz]=dirs[player.dir];rollVector={x:dx,z:dz};player.action='roll';player.elapsed=0;queuedRoll=false;rollStarts++;}
function action(kind){if(modal){dismiss();return;}if(!$('#help-panel').hidden)return;if(player.action==='roll'){if(kind==='interact')queuedRoll=true;return;}if(player.action==='attack')return;if(kind==='interact'&&nearby){$('#dialog-label').textContent=nearby.name.toUpperCase();$('#dialog-text').textContent=nearby.text;$('#dialog').hidden=false;modal=true;keys.clear();return;}if(kind==='interact'){startRoll();return;}player.action='attack';player.elapsed=0;}
document.addEventListener('keydown',e=>{if(e.target.closest?.('button')&&['Space','Enter'].includes(e.code))return;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space','KeyW','KeyA','KeyS','KeyD'].includes(e.code))e.preventDefault();if(e.repeat)return;keys.add(e.code);if(['KeyE','Space','Enter'].includes(e.code))action('interact');if(['KeyB','KeyX'].includes(e.code))action('attack');if(e.code==='Escape'){dismiss();$('#help-panel').hidden=true;}});
document.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',()=>{keys.clear();joystick={x:0,z:0};queuedRoll=false;});document.addEventListener('visibilitychange',()=>{keys.clear();joystick={x:0,z:0};queuedRoll=false;});
$('#dismiss').onclick=dismiss;$('#prompt').onclick=()=>action('interact');$('#help').onclick=()=>{$('#help-panel').hidden=!$('#help-panel').hidden;keys.clear();};$('#close-help').onclick=()=>$('#help-panel').hidden=true;
// Secondary touches do not reliably produce clicks. Trigger each action on its own
// pointer-down, and reserve click for keyboard/assistive activation to avoid doubles.
for(const [selector,kind] of [['#interact','interact'],['#attack','attack']]){const button=$(selector);let pressedPointer=null;const release=e=>{if(e&&e.pointerId!==pressedPointer)return;pressedPointer=null;button.classList.remove('is-pressed');};button.onpointerdown=e=>{if(e.button!==0||pressedPointer!==null)return;e.preventDefault();pressedPointer=e.pointerId;button.setPointerCapture(e.pointerId);button.classList.add('is-pressed');action(kind);};button.onpointerup=button.onpointercancel=button.onlostpointercapture=release;window.addEventListener('blur',()=>release());button.onclick=e=>{if(e.detail===0)action(kind);};}
const stick=$('#stick');let stickPointer=null;function stickMove(e){const r=stick.getBoundingClientRect(),dx=(e.clientX-r.left-r.width/2)/38,dz=(e.clientY-r.top-r.height/2)/38,l=Math.max(1,Math.hypot(dx,dz));joystick={x:dx/l,z:dz/l};$('#thumb').style.transform=`translate(${joystick.x*33}px,${joystick.z*33}px)`;}
stick.onpointerdown=e=>{if(stickPointer!==null)return;e.preventDefault();stickPointer=e.pointerId;stick.setPointerCapture(e.pointerId);stickMove(e);};stick.onpointermove=e=>{if(e.pointerId===stickPointer)stickMove(e)};function stickEnd(e){if(e.pointerId!==stickPointer)return;stickPointer=null;joystick={x:0,z:0};$('#thumb').style.transform='';}stick.onpointerup=stick.onpointercancel=stick.onlostpointercapture=stickEnd;
canvas.addEventListener('wheel',e=>{e.preventDefault();zoom=THREE.MathUtils.clamp(zoom*Math.exp(e.deltaY*.0006),.7,1.3);},{passive:false});const touches=new Map();let pinch=0;canvas.onpointerdown=e=>{touches.set(e.pointerId,[e.clientX,e.clientY]);canvas.setPointerCapture(e.pointerId);if(touches.size===2){const [a,b]=[...touches.values()];pinch=Math.hypot(a[0]-b[0],a[1]-b[1]);}};canvas.onpointermove=e=>{if(!touches.has(e.pointerId))return;touches.set(e.pointerId,[e.clientX,e.clientY]);if(touches.size===2){const [a,b]=[...touches.values()],d=Math.hypot(a[0]-b[0],a[1]-b[1]);if(pinch>0)zoom=THREE.MathUtils.clamp(zoom*pinch/d,.7,1.3);pinch=d;}};canvas.onpointerup=canvas.onpointercancel=e=>{touches.delete(e.pointerId);pinch=0;};

// Filmic tilt shift: a sharp band tracks the actor, with depth-aware foreground/background blur.
const target=new THREE.WebGLRenderTarget(1,1,{type:THREE.HalfFloatType,depthTexture:new THREE.DepthTexture(1,1)});target.samples=2;
const postScene=new THREE.Scene(),postCamera=new THREE.OrthographicCamera(-1,1,1,-1,0,1);
const postMat=new THREE.ShaderMaterial({uniforms:{tColor:{value:target.texture},tDepth:{value:target.depthTexture},resolution:{value:new THREE.Vector2()},focus:{value:15},focusY:{value:.5},near:{value:.1},far:{value:80}},vertexShader:'varying vec2 vUv;void main(){vUv=uv;gl_Position=vec4(position.xy,0.,1.);}',fragmentShader:`varying vec2 vUv;uniform sampler2D tColor,tDepth;uniform vec2 resolution;uniform float focus,focusY,near,far;
float depth(vec2 uv){float d=texture2D(tDepth,uv).x;return 2.*near*far/(far+near-(d*2.-1.)*(far-near));}
void main(){vec3 c=texture2D(tColor,vUv).rgb;float dist=abs(depth(vUv)-focus);float band=smoothstep(.14,.43,abs(vUv.y-focusY));float blur=min(3.2,smoothstep(2.,7.,dist)*2.2+band*1.8);vec3 sum=c*2.;vec3 bloom=vec3(0.);for(int i=0;i<12;i++){float a=float(i)*2.399963;vec2 v=vec2(cos(a),sin(a));sum+=texture2D(tColor,vUv+v*blur/resolution).rgb;vec3 b=texture2D(tColor,vUv+v*5./resolution).rgb;bloom+=max(b-vec3(1.15),vec3(0.));}c=sum/14.+bloom*.024;float vig=1.-.3*smoothstep(.25,.77,length((vUv-.5)*vec2(1.,.88)));c*=vig;gl_FragColor=vec4(c,1.);
#include <tonemapping_fragment>
#include <colorspace_fragment>
}`});postScene.add(new THREE.Mesh(new THREE.PlaneGeometry(2,2),postMat));
function resize(){const w=innerWidth,h=innerHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();const size=renderer.getDrawingBufferSize(new THREE.Vector2());target.setSize(size.x,size.y);postMat.uniforms.resolution.value.copy(size);}
window.addEventListener('resize',resize);resize();$('#loading').classList.add('done');
let elapsed=0,frameCount=0;const projected=new THREE.Vector3();
function animate(){requestAnimationFrame(animate);const dt=Math.min(clock.getDelta(),.04);elapsed+=dt;village.update(dt,elapsed,player);const progress=village.snapshot();$('#trail-count span').textContent=progress.cut?'Herbs cleared · '+progress.cut+' / '+progress.total:'Walk through the herbs · B to cut';
if(!modal&&$('#help-panel').hidden){if(['attack','roll'].includes(player.action)){player.elapsed+=dt;if(player.action==='attack'&&player.elapsed>=.14&&player.elapsed<.23)village.cut(player);if(player.action==='roll'){const t=player.elapsed/.54;const speed=t>.12&&t<.75?5:0;move(rollVector.x*speed*dt,rollVector.z*speed*dt);}if(player.action==='roll'&&queuedRoll&&player.elapsed>=.40)startRoll();else if(player.elapsed> (player.action==='roll'?.54:.48)){player.action='idle';player.elapsed=0;}}else{let x=(keys.has('ArrowRight')||keys.has('KeyD')?1:0)-(keys.has('ArrowLeft')||keys.has('KeyA')?1:0)+joystick.x,z=(keys.has('ArrowDown')||keys.has('KeyS')?1:0)-(keys.has('ArrowUp')||keys.has('KeyW')?1:0)+joystick.z;const len=Math.hypot(x,z);if(len>.15){if(len>1){x/=len;z/=len;}player.dir=Math.abs(x)>Math.abs(z)?x>0?'east':'west':z>0?'south':'north';player.action='walk';const multiplier=(keys.has('ShiftLeft')||keys.has('ShiftRight'))?movement.runMultiplier:movement.walkMultiplier;player.walkTime+=dt*multiplier;move(x*movement.base*multiplier*dt,z*movement.base*multiplier*dt);}else{player.action='idle';player.walkTime=0;}}}
pose();const floor=village.groundHeight(player.x,player.z);actor.position.set(player.x,floor+.008,player.z);shadow.position.set(player.x,floor+.004,player.z); // vertical billboard: feet remain on the floor
const aspect=innerWidth/innerHeight,distance=aspect<.8?14.2:13.5;const followX=player.x,followZ=player.z;
camera.position.lerp(new THREE.Vector3(followX,9.2*zoom,distance*zoom+followZ),.1);camera.lookAt(followX,.55,followZ-1.2);groundSprite(actor,camera);
const [dx,dz]=dirs[player.dir];nearby=interactables.find(o=>{let vx=o.x-player.x,vz=o.z-player.z;return Math.hypot(vx,vz)<o.r&&(vx*dx+vz*dz)>-.05;})||null;$('#prompt').hidden=!nearby||modal||!$('#help-panel').hidden;if(nearby)$('#prompt').textContent=(matchMedia('(any-pointer: coarse), (max-width: 900px)').matches?'A':'E')+' · '+nearby.name;
projected.set(player.x,.7,player.z).project(camera);postMat.uniforms.focusY.value=projected.y*.5+.5;const cp=new THREE.Vector3(player.x,.7,player.z).applyMatrix4(camera.matrixWorldInverse);postMat.uniforms.focus.value=-cp.z;
renderer.setRenderTarget(target);renderer.render(scene,camera);renderer.setRenderTarget(null);renderer.render(postScene,postCamera);frameCount++;
}
window.hd2d={snapshot:()=>({player:{...player},movement:{...movement,running:keys.has('ShiftLeft')||keys.has('ShiftRight')},roll:{queued:queuedRoll,starts:rollStarts},nearby:nearby?.name||null,modal,collisions,frameCount,zoom,village:village.snapshot(),grounding:{anchor:actor.userData.groundPose?.anchor,footY:actor.position.y,floor:village.groundHeight(player.x,player.z),minVertexY:Math.min(...Array.from(actor.geometry.attributes.position.array).filter((_,i)=>i%3===1))},spriteMaterial:actorMat.type,shadow:actor.castShadow,objects:scene.children.length,render:renderer.info.render,viewport:{width:innerWidth,height:innerHeight}})};animate();
