export const ENGINE_VERSION = 1;
export const PROFILE_STORAGE_KEY = "cairnloom-profile-v1";

export const MAP_WIDTH = 7;
export const MAP_HEIGHT = 12;
export const MIN_PATH_TILES = 12;
export const MIN_BUILD_PADS = 8;
export const TARGET_BUILD_PADS_MIN = 10;
export const TARGET_BUILD_PADS_MAX = 14;

export const FIXED_STEP_SECONDS = 1 / 30;
export const FIXED_STEP_MS = FIXED_STEP_SECONDS * 1000;
export const STARTING_GOLD = 180;
export const STARTING_BASE_HEALTH = 20;
export const DEFAULT_SELL_RATIO = 0.7;
export const MAX_TOWER_LEVEL = 4;

export const BIOMES = [
  { id: "emberwood", name: "The Emberwood", ground: "moss", accent: "ember" },
  { id: "cinderfen", name: "Cinderfen", ground: "peat", accent: "mana" },
  { id: "glassmoor", name: "The Glass Moor", ground: "obsidian", accent: "gold" },
  { id: "ashen-crown", name: "The Ashen Crown", ground: "ash", accent: "oxblood" },
];

export const TOWER_ARCHETYPES = {
  ashbolt: {
    id: "ashbolt",
    name: "Ashbolt Turret",
    shortName: "Ashbolt",
    role: "single",
    description: "Fast, reliable bolts against the enemy nearest the Ward.",
    initiallyUnlocked: true,
    unlockCost: 0,
    baseCost: 60,
    cost: 60,
    buildCost: 60,
    maxLevel: MAX_TOWER_LEVEL,
    maxMastery: 5,
    upgradeCosts: [42, 68, 100],
    damage: 13,
    range: 2.85,
    attackInterval: 0.68,
    icon: "bolt",
  },
  cinder_mortar: {
    id: "cinder_mortar",
    name: "Cinder Mortar",
    shortName: "Mortar",
    role: "aoe",
    description: "Lobs a slow ember shell that scorches a clustered group.",
    initiallyUnlocked: true,
    unlockCost: 0,
    baseCost: 85,
    cost: 85,
    buildCost: 85,
    maxLevel: MAX_TOWER_LEVEL,
    maxMastery: 5,
    upgradeCosts: [58, 86, 124],
    damage: 9,
    range: 2.75,
    attackInterval: 1.22,
    splashRadius: 1.12,
    icon: "burst",
  },
  brand_brazier: {
    id: "brand_brazier",
    name: "Brand Brazier",
    shortName: "Brazier",
    role: "dot",
    description: "Brands one foe with fire that keeps burning after the shot.",
    initiallyUnlocked: false,
    unlockCost: 55,
    baseCost: 76,
    cost: 76,
    buildCost: 76,
    maxLevel: MAX_TOWER_LEVEL,
    maxMastery: 5,
    upgradeCosts: [52, 78, 112],
    damage: 3,
    range: 2.7,
    attackInterval: 0.92,
    dotDamage: 3,
    dotInterval: 0.5,
    dotDuration: 3,
    icon: "brand",
  },
  rime_bell: {
    id: "rime_bell",
    name: "Rime Bell",
    shortName: "Rime Bell",
    role: "slow",
    description: "Tolls with winter magic, slowing the foremost invader.",
    initiallyUnlocked: false,
    unlockCost: 70,
    baseCost: 78,
    cost: 78,
    buildCost: 78,
    maxLevel: MAX_TOWER_LEVEL,
    maxMastery: 5,
    upgradeCosts: [54, 82, 116],
    damage: 5,
    range: 2.7,
    attackInterval: 0.95,
    slowMultiplier: 0.58,
    slowDuration: 2.45,
    icon: "snow",
  },
  storm_reliquary: {
    id: "storm_reliquary",
    name: "Storm Reliquary",
    shortName: "Reliquary",
    role: "chain",
    description: "Lightning jumps through a formation, weakening at every link.",
    initiallyUnlocked: false,
    unlockCost: 95,
    baseCost: 100,
    cost: 100,
    buildCost: 100,
    maxLevel: MAX_TOWER_LEVEL,
    maxMastery: 5,
    upgradeCosts: [70, 104, 148],
    damage: 14,
    range: 2.85,
    attackInterval: 1.04,
    chainCount: 4,
    chainRange: 1.75,
    chainFalloff: 0.68,
    icon: "chain",
  },
};

export const TOWER_ORDER = [
  "ashbolt",
  "cinder_mortar",
  "brand_brazier",
  "rime_bell",
  "storm_reliquary",
];

export const ENEMY_ARCHETYPES = {
  ashling: {
    id: "ashling",
    name: "Ashling",
    family: "common",
    availableFromWave: 1,
    budgetCost: 1,
    weight: 8,
    health: 23,
    speed: 0.72,
    armor: 0,
    shield: 0,
    leakDamage: 1,
    bounty: 1,
  },
  spark_mite: {
    id: "spark_mite",
    name: "Spark Mite",
    family: "swarm",
    availableFromWave: 2,
    budgetCost: 1,
    weight: 6,
    health: 14,
    speed: 1.16,
    armor: 0,
    shield: 0,
    leakDamage: 1,
    bounty: 1,
  },
  cinder_brute: {
    id: "cinder_brute",
    name: "Cinder Brute",
    family: "brute",
    availableFromWave: 3,
    budgetCost: 3,
    weight: 4,
    health: 59,
    speed: 0.5,
    armor: 0,
    shield: 0,
    leakDamage: 2,
    bounty: 3,
  },
  ironbound: {
    id: "ironbound",
    name: "Ironbound",
    family: "armored",
    availableFromWave: 4,
    budgetCost: 4,
    weight: 3,
    health: 52,
    speed: 0.54,
    armor: 4,
    shield: 0,
    leakDamage: 2,
    bounty: 4,
  },
  veil_wisp: {
    id: "veil_wisp",
    name: "Veil Wisp",
    family: "shielded",
    availableFromWave: 5,
    budgetCost: 3,
    weight: 4,
    health: 31,
    speed: 0.82,
    armor: 0,
    shield: 24,
    leakDamage: 1,
    bounty: 3,
  },
  siege_hulk: {
    id: "siege_hulk",
    name: "Siege Hulk",
    family: "tank",
    availableFromWave: 7,
    budgetCost: 6,
    weight: 2,
    health: 112,
    speed: 0.37,
    armor: 2,
    shield: 0,
    leakDamage: 3,
    bounty: 6,
  },
  ember_colossus: {
    id: "ember_colossus",
    name: "Ember Colossus",
    family: "boss",
    boss: true,
    availableFromWave: 10,
    budgetCost: 0,
    weight: 0,
    health: 560,
    speed: 0.34,
    armor: 4,
    shield: 145,
    leakDamage: 10,
    bounty: 30,
  },
};

export const NORMAL_ENEMY_IDS = [
  "ashling",
  "spark_mite",
  "cinder_brute",
  "ironbound",
  "veil_wisp",
  "siege_hulk",
];

export const BOSS_ENEMY_ID = "ember_colossus";

export const RELICS = {
  sharpened_embers: {
    id: "sharpened_embers",
    name: "Sharpened Embers",
    description: "+8% tower damage for this run.",
    effect: "damage",
    amount: 0.08,
    maxStacks: 3,
    rarity: "common",
  },
  clockwork_spring: {
    id: "clockwork_spring",
    name: "Clockwork Spring",
    description: "+7% tower attack speed for this run.",
    effect: "attack-speed",
    amount: 0.07,
    maxStacks: 3,
    rarity: "common",
  },
  surveyors_lens: {
    id: "surveyors_lens",
    name: "Surveyor's Lens",
    description: "+0.16 range to every tower for this run.",
    effect: "range",
    amount: 0.16,
    maxStacks: 3,
    rarity: "common",
  },
  bounty_seal: {
    id: "bounty_seal",
    name: "Bounty Seal",
    description: "+10% Gold from future waves this run.",
    effect: "wave-gold",
    amount: 0.1,
    maxStacks: 3,
    rarity: "common",
  },
  menders_thread: {
    id: "menders_thread",
    name: "Mender's Thread",
    description: "+3 maximum Ward health and repair 3 now.",
    effect: "ward-health",
    amount: 3,
    maxStacks: 3,
    rarity: "common",
  },
  builders_mark: {
    id: "builders_mark",
    name: "Builder's Mark",
    description: "Tower placement and upgrades cost 8% less this run.",
    effect: "build-discount",
    amount: 0.08,
    maxStacks: 3,
    rarity: "common",
  },
  hawkeye_string: {
    id: "hawkeye_string",
    name: "Hawkeye String",
    description: "Ashbolt Turrets deal 14% more damage this run.",
    effect: "tower-damage",
    amount: 0.14,
    maxStacks: 2,
    rarity: "specialized",
    towerId: "ashbolt",
  },
  scatter_charge: {
    id: "scatter_charge",
    name: "Scatter Charge",
    description: "Cinder Mortars gain +0.18 blast radius this run.",
    effect: "tower-special",
    amount: 0.18,
    maxStacks: 2,
    rarity: "specialized",
    towerId: "cinder_mortar",
  },
  hungry_oil: {
    id: "hungry_oil",
    name: "Hungry Oil",
    description: "Brand Brazier burns deal 18% more damage this run.",
    effect: "tower-special",
    amount: 0.18,
    maxStacks: 2,
    rarity: "specialized",
    towerId: "brand_brazier",
  },
  winter_clapper: {
    id: "winter_clapper",
    name: "Winter Clapper",
    description: "Rime Bell slows are 5% stronger this run.",
    effect: "tower-special",
    amount: 0.05,
    maxStacks: 2,
    rarity: "specialized",
    towerId: "rime_bell",
  },
  forked_sigil: {
    id: "forked_sigil",
    name: "Forked Sigil",
    description: "Storm Reliquary lightning gains one jump this run.",
    effect: "tower-special",
    amount: 1,
    maxStacks: 2,
    rarity: "specialized",
    towerId: "storm_reliquary",
  },
};

export const RELIC_ORDER = [
  "sharpened_embers",
  "clockwork_spring",
  "surveyors_lens",
  "bounty_seal",
  "menders_thread",
  "builders_mark",
  "hawkeye_string",
  "scatter_charge",
  "hungry_oil",
  "winter_clapper",
  "forked_sigil",
];

export const TALENT_TREE = {
  reinforced_foundation: {
    id: "reinforced_foundation",
    name: "Reinforced Foundation",
    description: "+2 maximum Ward health per rank.",
    maxLevel: 5,
    maxRank: 5,
    costs: [1, 1, 2, 2, 3],
    currency: "sigils",
    requires: null,
  },
  tempered_arsenal: {
    id: "tempered_arsenal",
    name: "Tempered Arsenal",
    description: "+4% damage across all towers per rank.",
    maxLevel: 5,
    maxRank: 5,
    costs: [1, 1, 2, 2, 3],
    currency: "sigils",
    requires: null,
  },
  quickened_gears: {
    id: "quickened_gears",
    name: "Quickened Gears",
    description: "+4% attack speed across all towers per rank.",
    maxLevel: 5,
    maxRank: 5,
    costs: [1, 2, 2, 3, 4],
    currency: "sigils",
    requires: { id: "tempered_arsenal", level: 2 },
  },
  war_chest: {
    id: "war_chest",
    name: "War Chest",
    description: "+15 starting Gold per rank.",
    maxLevel: 4,
    maxRank: 4,
    costs: [1, 1, 2, 3],
    currency: "sigils",
    requires: null,
  },
  bounty_oath: {
    id: "bounty_oath",
    name: "Bounty Oath",
    description: "+6% Gold earned between waves per rank.",
    maxLevel: 5,
    maxRank: 5,
    costs: [1, 2, 2, 3, 4],
    currency: "sigils",
    requires: { id: "war_chest", level: 2 },
  },
  keen_iron: {
    id: "keen_iron",
    name: "Keen Iron",
    description: "All tower hits ignore 1 Armor per rank.",
    maxLevel: 3,
    maxRank: 3,
    costs: [1, 2, 3],
    currency: "sigils",
    requires: { id: "tempered_arsenal", level: 2 },
  },
  deep_embers: {
    id: "deep_embers",
    name: "Deep Embers",
    description: "+8% Burn damage and status duration per rank.",
    maxLevel: 4,
    maxRank: 4,
    costs: [1, 2, 3, 4],
    currency: "sigils",
    requires: { id: "quickened_gears", level: 1 },
  },
  salvage_lore: {
    id: "salvage_lore",
    name: "Salvage Lore",
    description: "+4% of invested Gold returned when selling per rank.",
    maxLevel: 4,
    maxRank: 4,
    costs: [1, 1, 2, 3],
    currency: "sigils",
    requires: { id: "war_chest", level: 1 },
  },
  wardstone: {
    id: "wardstone",
    name: "Wardstone",
    description: "Repair 1 Ward health after a boss per rank.",
    maxLevel: 4,
    maxRank: 4,
    costs: [1, 2, 3, 4],
    currency: "sigils",
    requires: { id: "reinforced_foundation", level: 2 },
  },
  cinder_compact: {
    id: "cinder_compact",
    name: "Cinder Compact",
    description: "+10% Cinders carried home after defeat per rank.",
    maxLevel: 4,
    maxRank: 4,
    costs: [1, 2, 3, 4],
    currency: "sigils",
    requires: { id: "bounty_oath", level: 2 },
  },
};

export const TALENT_ORDER = [
  "reinforced_foundation",
  "tempered_arsenal",
  "quickened_gears",
  "war_chest",
  "bounty_oath",
  "keen_iron",
  "deep_embers",
  "salvage_lore",
  "wardstone",
  "cinder_compact",
];
